---
ahoyapi: v2

commands:
  up:
    usage: Build project.
    cmd: docker-compose up -d "$@"

  down:
    usage: Delete project.
    cmd: docker-compose down

  build:
    usage: Build project.
    cmd: docker-compose up -d --build "$@"

  cli:
    usage: Start a shell inside TEST container.
    cmd: docker-compose exec test bash

  cli-nginx:
    usage: Start a shell inside TEST container.
    cmd: docker-compose exec nginx sh

  run:
    usage: Run command inside TEST container.
    cmd: docker-compose exec -T test bash -c "$@"

  drush:
    usage: Run drush commands in TEST container.
    cmd: docker-compose exec -T test drush "$@"

  logs:
    usage: Show Docker logs.
    cmd: docker-compose logs "$@"

#  ps:
#    usage: List running Docker containers.
#    cmd: docker-compose ps
#
  restart:
    usage: Restart Docker containers.
    cmd: docker-compose restart

  stop:
    usage: Stop Docker containers.
    cmd: docker-compose stop "$@"

  install:
    usage: Install the GovCMS profile.
    cmd: docker-compose exec -T test drush si -y govcms "$@"

#
#  login:
#    usage: Login to a website.
#    cmd: docker-compose exec -T test drush uli "$@"

  pull:
    usage: Pull latest docker images.
    cmd: docker image ls --format \"{{.Repository}}:{{.Tag}}\" | grep govcms8lagoon/ | grep -v none | xargs -n1 docker pull | cat

  push:
    usage: Push all docker images.
    cmd: |
      export $(grep -v '^#' .env.default | xargs)
      . .docker/push.sh

  release:
    usage: Push all docker images.
    cmd: |
      export $(grep -v '^#' .env.default | xargs)
      . .docker/release.sh

  audit-site:
    usage: Run site audit
    cmd: docker-compose exec -T test drutiny profile:run d8-full @self "$@"

  lint:
    usage: Lint code
    cmd: docker-compose exec test lint-govcms

  test:
    usage: Run all tests.
    cmd: |
      ahoy test-phpunit
      ahoy test-behat
  test-behat:
    usage: Run Behat tests.
    cmd: docker-compose exec test behat "$@"

  test-phpunit:
    usage: Run PHPUnit tests.
    cmd: docker-compose exec test phpunit "$@"

#hihihih